# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publish',
            old_name='desc',
            new_name='description',
        ),
        migrations.AddField(
            model_name='publish',
            name='pet',
            field=models.ManyToManyField(related_name='Publishs', to='pet.Pet'),
        ),
    ]
