# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 00:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_publish_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='publish_set', to=settings.AUTH_USER_MODEL, verbose_name='宠物主人'),
        ),
    ]
