# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0006_auto_20181008_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publish',
            name='uuid',
        ),
    ]
