# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 18:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_pet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='{0!s}.format(self.id)', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='add_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.DurationField(blank=True, max_length=20, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(default='宠物', max_length=10, verbose_name='宠物名称'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('large', '大型'), ('medium', '中等体型'), ('small', '小型')], max_length=6, verbose_name='尺寸'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('cat', '猫'), ('dog', '狗')], max_length=3, verbose_name='宠物类型'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='宠物主人'),
        ),
    ]
