# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_auto_20181006_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='年龄'),
        ),
    ]
