# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_auto_20181006_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='adopted',
            field=models.BooleanField(default=False, verbose_name='已被领养'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='<built-in function id>', verbose_name='图片'),
        ),
    ]
