# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_auto_20181006_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Pet.id', verbose_name='图片'),
        ),
    ]
