# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import pet.models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_auto_20181006_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=pet.models.upload_to, verbose_name='图片'),
        ),
    ]
