# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181006_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='category',
            field=models.CharField(choices=[('out', '宠物领养'), ('in', '宠物送养')], default='out', max_length=10, verbose_name='是否领养'),
        ),
    ]
