# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181009_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('male', '先生'), ('female', '女士')], max_length=6, verbose_name='性别'),
        ),
    ]
